modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/PssbleTrngle/Dungeon/issues"
license="https://github.com/PssbleTrngle/Dungeon/blob/master/LICENSE.txt"

[[mods]]
    modId="brazier"
    version="${file.jarVersion}"
    displayName="Dungeon"
    authors="possible_triangle"
    description='''Generate an infinite dungeon'''

[[dependencies.brazier]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brazier]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

