modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/PssbleTrngle/Dungeon/issues"

[[mods]]
modId="dungeon"
version="${file.jarVersion}"
displayName="Dungeon"
authors='possible_triangle'
description='''
Generate an infinite dungeon.
'''

[[dependencies.dungeon]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
