name: Release

on:
  pull_request:
    types: [closed]
    branches:
    - master

jobs:
  
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: echo ${{ github.event }} | python -m json.tool
      
  publish:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v1.0.0
        with:
          name: built
          path: build/libs
