name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: chmod +x ./gradlew
      
    - run: ./gradlew build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: built
        path: ./
      
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: built

      - if: github.action == 'closed' && github.pull_request.merged == 'true'
        run: echo Release
