name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: chmod +x ./gradlew
      
    - run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: build
