name: Test

on:
  repository_dispatch:
    types: test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: chmod +x ./gradlew
      
    - name: Setup project
    - run: ./gradlew build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: built
        path: ./

  test:
    if: github.event.action == 'test' || github.event_name != 'repository_dispatch'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: built
